### ISSUE TITLE
TypeError: dart.global.GoogleMediaPipeFaceDetectorWrapper is not a constructor

### ISSUE THREAD

**Issue by crushman1** [TecHaxter/google_mediapipe_face_detection#1]
Error when loading plugin on web. i suspect there might be some script missing in index.html but i dont know what.
```
 Future initializeModel() async {
    faceDetection = GoogleMediapipeFaceDetection();
    await faceDetection?.load();  // <-- error when loading
  }
```

**Comment by TecHaxter** [comment]
This is happening because the web plugin is not waiting for the JS Wrapper script to be loaded in the HTML DOM, and without waiting it is calling the load method.
I'll create a PR for this.

**Comment by TecHaxter** [comment]
Can you import the [issue_1](https://github.com/TecHaxter/google_mediapipe_face_detection/tree/issue_1) branch in pubspec.yaml like this:

```
  google_mediapipe_face_detection:
    git:
      url: git@github.com:TecHaxter/google_mediapipe_face_detection.git
      ref: issue_1
```

After your feedback, I will merge this branch and publish the updated version.

**Comment by crushman1** [comment]
I hope i dont sound to newbie but when i add this it says i may not have the right access rights ? 
```
Git error. Command: `git clone --mirror git@github.com:TecHaxter/google_mediapipe_face_detection.git /Users/mypcname/.pub-cache/git/cache/google_mediapipe_face_detection-4edd7f3759f2b5f3c6e9468807e5be04c61a502d`
stdout: 
stderr: Cloning into bare repository '/Users/mypcname/.pub-cache/git/cache/google_mediapipe_face_detection-4edd7f3759f2b5f3c6e9468807e5be04c61a502d'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
```

**Comment by crushman1** [comment]
It seems to be working. Thanks. response from `final res = await faceDetection?.processImage(inputImage);` is `[Rect.fromLTRB(298.0, 218.0, 474.0, 394.0)]` 
```
  google_mediapipe_face_detection:
    git:
      url: https://github.com/TecHaxter/google_mediapipe_face_detection.git
      ref: issue_1
```
